# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/reference-2-1/#section=configuration for more details

version: 2.1

references:
  working_directory: /tmp/gh-pages
  defaults: &defaults
    docker:
      - image: node:12.6

  # Install gulp & deps
  npm_install: &npm_install
    run:
      name: install-npm-dependencies
      command: |
        npm install
  # Update dashboard data files
  update_dashboard_data: &update_dashboard_data
    run:
      name: Update dashboard data
      command: |
        git config --global user.email no-reply@teamdigitale.governo.it
        git config --global user.name "Deploy Bot"
        git pull

        if [ `curl -s -w "%{http_code}" --compress -o /tmp/dashboardData.json https://dashboard.anpr.it/api/dashboard/data.json` = "200" ]; then
          if [ $(stat --printf="%s" /tmp/dashboardData.json) -gt 2000000 ]; then
            echo "dashboard data updated" && \
            cp /tmp/dashboardData.json .
          fi
        fi

        git commit -a  -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1} [ci skip]"
        git push origin $CIRCLE_BRANCH
  # Optimize site files with gulp
  gulp_build: &gulp_build
    run:
      name: gulp-build
      command: |
        npx gulp clean
        npx gulp
        git add docs
        git commit docs -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1} [ci skip]"
        git push origin $CIRCLE_BRANCH
  create_cname: &create_cname
    run:
      name: create-cname
      command: |
        echo "stato-migrazione.anpr.it" > docs/CNAME
        git add docs/CNAME
        git commit docs/CNAME -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1} [ci skip]"
        git push origin $CIRCLE_BRANCH

  # In order to use this, the integration needs to be
  # setup first under CircleCI app directory and a
  # SLACK_WEBOOK environment variable needs to be set
  # in the project settings
  notify_on_failure: &notify_on_failure
    slack/status:
      fail_only: true
      only_for_branches: master

jobs:
  update:
    <<: *defaults
    steps:
      # Deploy the site to GitHub Pages
      #- add_ssh_keys: *add_ssh_keys
      - checkout
      - << : *npm_install
      - << : *update_dashboard_data
      - << : *gulp_build
      - << : *create_cname
      - << : *notify_on_failure

orbs:
  slack: circleci/slack@3.4.2

# This workflow will update the site every hour
workflows:
  version: 2
  # For each commit on the master branch
  # deploy to VMs and to gh-pages
  on-master-commit-update-dashboard:
    jobs:
      - update:
          filters:
            branches:
              only:
                - master
  update-dashboard:
    triggers:
      - schedule:
          cron: "35 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - update
