# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ for more details
#

references:
  working_directory: /tmp/gh-pages
  defaults: &defaults
    docker:
      - image: node:12.6

  # Install gulp & deps
  npm_install: &npm_install
    run:
      name: install-npm-dependencies
      command: |
        npm install
  # Optimize site files with gulp
  gulp_build_and_publish: &gulp_build_and_publish
    run:
      name: gulp-build
      command: |
        npx gulp clean
        npx gulp

        echo stato-migrazione.anpr.it > docs/CNAME
        npx gh-pages -m 'Automated deployment: ${CIRCLE_SHA1} [ci skip]' -u 'Deploy Bot <no-reply@teamdigitale.governo.it>' -d docs

version: 2
jobs:
  update:
    <<: *defaults
    steps:
      # Deploy the site to GitHub Pages
      #- add_ssh_keys: *add_ssh_keys
      - checkout
      - << : *npm_install
      - << : *gulp_build_and_publish

# This workflow will update the site every hour
workflows:
  version: 2
  # For each commit on the master branch
  # deploy to VMs and to gh-pages
  on-master-commit-update-dashboard:
    jobs:
      - update:
          filters:
            branches:
              only:
                - master
