# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ for more details
#

references:
  working_directory: /tmp/gh-pages
  defaults: &defaults
    docker:
      - image: node:12.6

  # Install gulp & deps
  npm_install: &npm_install
    run:
      name: install-npm-dependencies
      command: |
        npm install
  # Optimize site files with gulp
  gulp_build: &gulp_build
    run:
      name: gulp-build
      command: |
        npx gulp clean
        npx gulp
        git add docs
        git commit docs -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1} [ci skip]"
        git push origin $CIRCLE_BRANCH
  create_cname: &create_cname
    run:
      name: create-cname
      command: |
        echo "stato-migrazione.anpr.it" > docs/CNAME
        git add docs/CNAME
        git commit docs/CNAME -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1} [ci skip]"
        git push origin $CIRCLE_BRANCH

version: 2
jobs:
  update:
    <<: *defaults
    steps:
      # Deploy the site to GitHub Pages
      #- add_ssh_keys: *add_ssh_keys
      - checkout
      - << : *npm_install
      - << : *gulp_build
      - << : *create_cname

# This workflow will update the site every hour
workflows:
  version: 2
  # For each commit on the master branch
  # deploy to VMs and to gh-pages
  on-master-commit-update-dashboard:
    jobs:
      - update:
          filters:
            branches:
              only:
                - master
